#!/usr/bin/env python3
"""
Build the Continuous-Day v2 demand profile (2026-06-13).

Replaces the five disjoint constant-demand scenarios with ONE realistic day:
quiet dawn → morning rush BUILDS (N-heavy) → peak → eases → midday lull →
evening rush builds (S-heavy) → peak → quiets. The model trains on a real-time
stream and must learn the TRANSITIONS — and notice the load flip from
northbound (commute in) to southbound (commute out) — not just steady states.

Built by blending three already-validated, known-solvable demand templates so
every point on the curve sits within the junction's protected-left capacity:
  off_peak (1150, balanced) · morning_rush (1901, N-heavy) · evening_rush (2350, S-heavy)

A 7200s episode is treated as a compressed day (same length as v1 episodes, so
no env change). Demand is sampled in STEP-second windows along a piecewise-linear
weight curve over the three templates.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SC = ROOT / "simulation" / "scenarios"
OUT = SC / "continuous_day.rou.xml"
DAY = 7200
STEP = 300            # window length (s) — 24 windows; small enough for smooth ramps


def template(name: str) -> dict:
    """{flow_id: (type, route, vehsPerHour)} for a scenario's car/trotro flows."""
    txt = (SC / f"{name}.rou.xml").read_text()
    out = {}
    for m in re.finditer(
            r'<flow id="([^"]+)" type="([^"]+)" route="([^"]+)"\s*'
            r'begin="[^"]*" end="[^"]*" vehsPerHour="([\d.]+)"', txt):
        out[m.group(1)] = (m.group(2), m.group(3), float(m.group(4)))
    return out


OFF  = template("off_peak")
MORN = template("morning_rush")
EVE  = template("evening_rush")
FLOW_IDS = list(MORN.keys())          # all three share the same 15 flow ids

# ── Day shape: keyframes of (time_s, w_off, w_morning, w_evening) ─────────────
# Weights blend the three templates; they need not sum to 1 (a lull can be a
# fraction of off-peak). Linear interpolation between keyframes.
KEYFRAMES = [
    (0,    1.0, 0.0, 0.0),   # 00:00 night / dawn — quiet (1150)
    (900,  1.0, 0.0, 0.0),   #       hold quiet
    (1500, 0.3, 0.7, 0.0),   # morning BUILD — northbound commute ramps in
    (2400, 0.0, 1.0, 0.0),   # MORNING PEAK — N-heavy 1901
    (3000, 0.0, 1.0, 0.0),   #       hold peak
    (3600, 0.5, 0.5, 0.0),   # morning eases
    (4200, 1.0, 0.0, 0.0),   # MIDDAY LULL — back to 1150
    (4800, 1.0, 0.0, 0.0),   #       hold lull
    (5400, 0.3, 0.0, 0.7),   # evening BUILD — load FLIPS to southbound
    (6000, 0.0, 0.0, 1.0),   # EVENING PEAK — S-heavy 2350
    (6600, 0.0, 0.0, 1.0),   #       hold peak
    (7200, 1.0, 0.0, 0.0),   # night — quiets back down
]


def weights_at(t: float) -> tuple:
    for i in range(len(KEYFRAMES) - 1):
        t0, *w0 = KEYFRAMES[i]
        t1, *w1 = KEYFRAMES[i + 1]
        if t0 <= t <= t1:
            f = 0.0 if t1 == t0 else (t - t0) / (t1 - t0)
            return tuple(a + (b - a) * f for a, b in zip(w0, w1))
    return tuple(KEYFRAMES[-1][1:])


def header() -> str:
    """vType + route block, copied verbatim from morning_rush (canonical)."""
    txt = (SC / "morning_rush.rou.xml").read_text()
    start = txt.index("<routes>") + len("<routes>")
    end = txt.index("<!-- Flows")
    return txt[start:end]


def ped_block() -> str:
    txt = (SC / "morning_rush.rou.xml").read_text()
    start = txt.index("<!-- Pedestrian crossing flows -->")
    end = txt.index("</routes>")
    return txt[start:end]


# ── Emit ─────────────────────────────────────────────────────────────────────
lines = ['<?xml version="1.0" encoding="UTF-8"?>',
         '<!--',
         '  ATCS-GH | Continuous-Day v2 — one realistic day on the Achimota junction.',
         '  quiet → morning rush (N-heavy 1901) → midday lull → evening rush (S-heavy 2350) → quiet.',
         '  Generated by build_continuous_day.py — blends off_peak/morning/evening templates.',
         '-->',
         '<routes>',
         header().rstrip(),
         '',
         '  <!-- Time-varying demand: 24 windows along the day curve -->']

n_win = DAY // STEP
peak_total = 0.0
for w in range(n_win):
    t0 = w * STEP
    t1 = t0 + STEP
    wo, wm, we = weights_at(t0 + STEP / 2.0)
    win_total = 0.0
    for fid in FLOW_IDS:
        ty, rt, _ = MORN[fid]
        vph = (wo * OFF[fid][2] + wm * MORN[fid][2] + we * EVE[fid][2])
        win_total += vph
        if vph < 0.05:
            continue
        lines.append(
            f'  <flow id="{fid}_w{w:02d}" type="{ty}" route="{rt}" '
            f'begin="{t0}" end="{t1}" vehsPerHour="{vph:.1f}" '
            f'departLane="best" departSpeed="max"/>')
    peak_total = max(peak_total, win_total)

lines.append('')
lines.append(ped_block().rstrip())
lines.append('</routes>')
OUT.write_text("\n".join(lines) + "\n")

# ── Report the curve ─────────────────────────────────────────────────────────
print(f"wrote {OUT}  ({n_win} windows × {len(FLOW_IDS)} flows, peak ~{peak_total:.0f} veh/hr)")
print("\n  day curve (per window: total veh/hr, N/S/E/W approach split):")
for w in range(n_win):
    t0 = w * STEP
    wo, wm, we = weights_at(t0 + STEP / 2.0)
    appr = {"N": 0.0, "S": 0.0, "E": 0.0, "W": 0.0}
    tot = 0.0
    for fid in FLOW_IDS:
        rt = MORN[fid][1]
        vph = wo * OFF[fid][2] + wm * MORN[fid][2] + we * EVE[fid][2]
        appr[rt.split("_")[1][0]] += vph
        tot += vph
    bar = "█" * int(tot / 60)
    hh = int(6 + t0 / DAY * 18)   # label as a rough clock 06:00→24:00
    mm = int((t0 / DAY * 18 * 60) % 60)
    print(f"   {hh:02d}:{mm:02d}  {tot:5.0f}  N{appr['N']:4.0f} S{appr['S']:4.0f} "
          f"E{appr['E']:4.0f} W{appr['W']:4.0f}  {bar}")
